# Frontend Dockerfile
FROM node:18-alpine

WORKDIR /app

COPY ./Frontend/package*.json ./
RUN npm  install --legacy-peer-deps

COPY ./Frontend .

RUN npm run build

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
