services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '5001:5001'
    env_file:
      - Backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    env_file:
      - Frontend/.env.development

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
